#!/usr/bin/env node
// Vendor the tv-dev-skills skill files into a project and wire up a router
// block for agents that don't have Claude Code's on-demand skill loading
// (Codex / AGENTS.md, Cursor, GitHub Copilot).
//
// Usage:
//   node tools/install.mjs [--dir=.] [--dest=.agent-skills/tv-dev-skills]
//                          [--targets=agents,cursor,copilot] [--dry-run]
//
// Or, without cloning:
//   npx github:rafaeltscs/tv-dev-skills --dir=/path/to/your/app
//
// Re-run any time to pick up skill updates: the AGENTS.md / Copilot blocks
// are marker-delimited and replaced in place, and the Cursor rule files are
// regenerated (stale tv-dev-skills-*.mdc are pruned).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_URL = "https://github.com/rafaeltscs/tv-dev-skills";
const MARKER_ID = "tv-dev-skills";
const BEGIN = `<!-- BEGIN AUTOGENERATED: ${MARKER_ID} -->`;
const END = `<!-- END AUTOGENERATED: ${MARKER_ID} -->`;

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const skillsSrc = path.join(repoRoot, "skills");

// ---- args -----------------------------------------------------------------

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const m = a.match(/^--([^=]+)(?:=(.*))?$/);
    return m ? [m[1], m[2] ?? true] : [a, true];
  }),
);

if (args.help || args.h) {
  console.log(
    [
      "Vendor tv-dev-skills into a project and wire up an agent router block.",
      "",
      "  --dir=PATH       target project root (default: current directory)",
      "  --dest=PATH      where to copy skills, relative to --dir",
      "                   (default: .agent-skills/tv-dev-skills)",
      "  --targets=LIST   comma-separated: agents,cursor,copilot (default: all)",
      "  --dry-run        print planned writes, change nothing",
      "",
      `Source: ${REPO_URL}`,
    ].join("\n"),
  );
  process.exit(0);
}

const targetDir = path.resolve(String(args.dir || "."));

if (targetDir === repoRoot) {
  console.error(
    "Refusing to install into the tv-dev-skills repo itself.\n" +
      "Run this from your project, or pass --dir=/path/to/your/app.",
  );
  process.exit(1);
}
const destRel = String(args.dest || ".agent-skills/tv-dev-skills").replace(/\\/g, "/");
const destAbs = path.join(targetDir, destRel);
const targets = new Set(
  String(args.targets || "agents,cursor,copilot")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean),
);
const dryRun = Boolean(args["dry-run"]);

// ---- helpers ------------------------------------------------------------------

function parseFrontmatter(md) {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const out = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (kv) out[kv[1]] = kv[2].trim();
  }
  return out;
}

// First sentence of a skill description, for the compact router table.
// The full trigger criteria stay in each SKILL.md's frontmatter.
function firstSentence(desc) {
  const s = String(desc).replace(/\s+/g, " ").trim();
  const dot = s.indexOf(". ");
  const head = dot === -1 ? s : s.slice(0, dot + 1);
  return head.length > 320 ? head.slice(0, 317).trimEnd() + "…" : head;
}

function readSkills() {
  const dirs = fs
    .readdirSync(skillsSrc, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
  const skills = [];
  for (const name of dirs) {
    const skillMd = path.join(skillsSrc, name, "SKILL.md");
    if (!fs.existsSync(skillMd)) continue;
    const md = fs.readFileSync(skillMd, "utf8");
    const fm = parseFrontmatter(md);
    const description = fm.description || "";
    const placeholder = /^PLACEHOLDER\b/i.test(description);
    skills.push({ name: fm.name || name, dir: name, description, placeholder });
  }
  return skills;
}

const planned = [];
function write(file, content) {
  planned.push(path.relative(targetDir, file) || file);
  if (dryRun) return;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function upsertBlock(file, block, headerIfNew) {
  let existing = "";
  try {
    existing = fs.readFileSync(file, "utf8");
  } catch {
    /* new file */
  }
  const wrapped = `${BEGIN}\n${block}\n${END}`;
  let next;
  if (existing.includes(BEGIN) && existing.includes(END)) {
    next = existing.replace(
      new RegExp(`${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}`),
      wrapped,
    );
  } else if (existing.trim()) {
    next = `${existing.replace(/\s*$/, "")}\n\n${wrapped}\n`;
  } else {
    next = `${headerIfNew}${wrapped}\n`;
  }
  if (next !== existing) write(file, next);
  else planned.push(`${path.relative(targetDir, file)} (unchanged)`);
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ---- copy skills -----------------------------------------------------------

const skills = readSkills();
const real = skills.filter((s) => !s.placeholder);

if (real.length === 0) {
  console.error(`No skills found under ${skillsSrc}`);
  process.exit(1);
}

if (!dryRun) fs.mkdirSync(destAbs, { recursive: true });
for (const s of real) {
  const from = path.join(skillsSrc, s.dir);
  const to = path.join(destAbs, s.dir);
  planned.push(`${path.relative(targetDir, to)}/  (skill files)`);
  if (!dryRun) {
    fs.rmSync(to, { recursive: true, force: true });
    fs.cpSync(from, to, { recursive: true });
  }
}

const destPosix = destRel.replace(/\\/g, "/");

// ---- router block (AGENTS.md + Copilot) ----------------------------------

function routerBlock() {
  const rows = real
    .map(
      (s) =>
        `| \`${s.name}\` | ${firstSentence(s.description)} | \`${destPosix}/${s.dir}/SKILL.md\` |`,
    )
    .join("\n");
  return [
    `## TV/OTT development skills`,
    ``,
    `This project vendors [tv-dev-skills](${REPO_URL}) under \`${destPosix}/\`.`,
    `Each skill covers a domain where TV/OTT development diverges sharply from`,
    `web/mobile work (no DOM, remote-control focus, low-end hardware, a`,
    `fragmented platform landscape). The skill bodies are large and load-on-`,
    `demand by design — **do not paste them in wholesale.** When a task matches`,
    `a row below, open that \`SKILL.md\` first and follow it (it will point you`,
    `to the \`references/\` files it needs); otherwise ignore them.`,
    ``,
    `| Skill | Read it when the task involves… | File |`,
    `|---|---|---|`,
    rows,
    ``,
    `Full trigger criteria are in each \`SKILL.md\`'s frontmatter. This block is`,
    `generated — re-run the tv-dev-skills installer to update it.`,
  ].join("\n");
}

if (targets.has("agents")) {
  upsertBlock(
    path.join(targetDir, "AGENTS.md"),
    routerBlock(),
    `# AGENTS.md\n\nInstructions for coding agents working in this repo.\n\n`,
  );
}

if (targets.has("copilot")) {
  upsertBlock(
    path.join(targetDir, ".github", "copilot-instructions.md"),
    routerBlock(),
    `# Copilot instructions\n\n`,
  );
}

// ---- Cursor rules (one .mdc per skill) ----------------------------------

if (targets.has("cursor")) {
  const rulesDir = path.join(targetDir, ".cursor", "rules");
  // Prune stale generated rules first.
  try {
    for (const f of fs.readdirSync(rulesDir)) {
      if (/^tv-dev-skills-.*\.mdc$/.test(f)) {
        const keep = real.some((s) => `tv-dev-skills-${s.dir}.mdc` === f);
        if (!keep) {
          planned.push(`${path.relative(targetDir, path.join(rulesDir, f))} (removed)`);
          if (!dryRun) fs.rmSync(path.join(rulesDir, f));
        }
      }
    }
  } catch {
    /* no rules dir yet */
  }

  for (const s of real) {
    const desc = String(s.description).replace(/\s+/g, " ").trim();
    const body = [
      `---`,
      `description: ${desc}`,
      `alwaysApply: false`,
      `---`,
      ``,
      `# tv-dev-skills: ${s.name}`,
      ``,
      `When this rule is attached, read the vendored skill before writing or`,
      `reviewing code:`,
      ``,
      `1. \`${destPosix}/${s.dir}/SKILL.md\``,
      `2. Any files it references under \`${destPosix}/${s.dir}/references/\``,
      ``,
      `Follow that skill's guidance. Source: ${REPO_URL}`,
      ``,
    ].join("\n");
    write(path.join(rulesDir, `tv-dev-skills-${s.dir}.mdc`), body);
  }
}

// ---- report -------------------------------------------------------------

console.log(dryRun ? "Planned changes (dry run):" : "Wrote:");
for (const p of planned) console.log(`  ${p}`);
console.log(
  `\n${real.length} skill(s) vendored to ${destPosix}/  ·  targets: ${[...targets].join(", ")}`,
);
if (skills.some((s) => s.placeholder)) {
  const names = skills.filter((s) => s.placeholder).map((s) => s.name).join(", ");
  console.log(`Skipped placeholder skill(s): ${names}`);
}
